### ISSUE TITLE
R6 cog having pillow issues when installing.

### ISSUE THREAD

**Issue by DanteMccloud** [flaree/flare-cogs#120]
**Describe the bug**
Fails to install the r6 cog everytime I try I get the error below. I tried to bypass it by manually installing pillow in CMD using pip3 install pillow but that didn't seem to help anything.

[11:50:19] ERROR    ERROR: Exception:                                           [red.downloader]
                    Traceback (most recent call last):
                      File "c:\users\administrator\redenv\lib\site-packages\pip
                    \_internal\cli\base_command.py", line 180, in _main
                        status = self.run(options, args)
                      File "c:\users\administrator\redenv\lib\site-packages\pip
                    \_internal\cli\req_command.py", line 204, in wrapper
                        return func(self, options, args)
                      File "c:\users\administrator\redenv\lib\site-packages\pip
                    \_internal\commands\install.py", line 449, in run
                        self._handle_target_dir(
                      File "c:\users\administrator\redenv\lib\site-packages\pip
                    \_internal\commands\install.py", line 503, in
                    _handle_target_dir
                        shutil.rmtree(target_item_dir)
                      File "C:\Python38\lib\shutil.py", line 740, in rmtree
                        return _rmtree_unsafe(path, onerror)
                      File "C:\Python38\lib\shutil.py", line 618, in
                    _rmtree_unsafe
                        onerror(os.unlink, fullname, sys.exc_info())
                      File "C:\Python38\lib\shutil.py", line 616, in
                    _rmtree_unsafe
                        os.unlink(fullname)
                    PermissionError: [WinError 5] Access is denied: 'C:\\Users\
                    \Administrator\\AppData\\Local\\Red-DiscordBot\\Red-Discord
                    Bot\\data\\ExpeditionBot\\cogs\\Downloader\\lib\\PIL\\_imag
                    ing.cp38-win_amd64.pyd'
[11:50:32] ERROR    Something went wrong when installing the following          [red.downloader]
                    requirements: pillow

**Comment by flaree** [comment]
Fix errors when trying to load a cog that requires pillow

• Turn off your bot.
• Open the command line for your OS.
• Activate the VENV your bot is installed in.
• Run the following commands in order, one after another:
`pip uninstall pillow`
`pip uninstall PIL;
`pip install --force-reinstall --no-cache-dir wheel setuptools`
 pip install --force-reinstall --no-cache-dir pillow`
• Start up your bot.
• Load the fussy cog.

Follow these and it should work.

**Comment by DanteMccloud** [comment]
that fixed it not sure why it happened but that did it :) thank you.
