### ISSUE TITLE
[p]userinfo on @bot results in AttributeError: 'ClientUser' object has no attribute 'mutual_guilds'

### ISSUE THREAD

**Issue by Skyridr** [flaree/flare-cogs#122]
When attempting to use the userinfo cog on a bot user, you'll get a `Error in command 'userinfo'. Check your console or logs for details` with the following traceback:

```py
Exception in command 'userinfo'
Traceback (most recent call last):
  File "/home/twds/.virtualenvs/twds/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/twds/twds/cogs/CogManager/cogs/userinfo/userinfo.py", line 178, in userinfo
    sharedguilds = user.mutual_guilds
AttributeError: 'ClientUser' object has no attribute 'mutual_guilds'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/twds/.virtualenvs/twds/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/twds/.virtualenvs/twds/lib/python3.8/site-packages/discord/ext/commands/core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/twds/.virtualenvs/twds/lib/python3.8/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'ClientUser' object has no attribute 'mutual_guilds'
```

**Comment by flaree** [comment]
Was the command done on your own bot or another?

**Comment by Skyridr** [comment]
That's a very good point. Out of the 2 bots, seems to be triggering the error on itself.

**Comment by flaree** [comment]
Let me know if 1aa08722326e37233080140f8904f3486b077a5c resolves this.

**Comment by Skyridr** [comment]
Works perfectly now, thanks! :D
