### ISSUE TITLE
Loading F1 cog does not work because of missing module

### ISSUE THREAD

**Issue by carstenflokstra** [flaree/flare-cogs#140]
**Describe the bug**
Loading module F1 results in an error of not finding the module Tabulate. Installed it manually into the Docker Environment, but no results either.

`ModuleNotFoundError: No module named 'tabulate'
[2021-12-06 17:46:34] [ERROR] red: Package loading failed
Traceback (most recent call last):
File "/data/venv/lib/python3.8/site-packages/redbot/core/core_commands.py", line 176, in _load
await bot.load_extension(spec)
File "/data/venv/lib/python3.8/site-packages/redbot/core/bot.py", line 1510, in load_extension
lib = spec.loader.load_module()
File "<frozen importlib._bootstrap_external>", line 522, in _check_name_wrapper
File "<frozen importlib._bootstrap_external>", line 1022, in load_module
File "<frozen importlib._bootstrap_external>", line 847, in load_module
File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
File "<frozen importlib._bootstrap>", line 702, in _load
File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 843, in exec_module
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "/data/cogs/CogManager/cogs/f1/__init__.py", line 1, in <module>
from .f1 import F1
File "/data/cogs/CogManager/cogs/f1/f1.py", line 7, in <module>
import tabulate
ModuleNotFoundError: No module named 'tabulate'`

**Output of [p]help CogName and [p]debuginfo**
# Debug Info for Red:

## System Metadata:
CPU Cores: 8 (x86_64)
RAM: 2.6GB/7.7GB (45.8%)

## OS Variables:
OS version: Debian GNU/Linux 11
User: docker
Python executable: /data/venv/bin/python
Python version: 3.8.12 (64bit)
Pip version: 21.3.1
Red version: 3.4.14
Discord.py version: 1.7.3

## Red variables:
Instance name: docker
Owner(s): 238674481470504964 (ItsFlokkie#0001)
Storage type: JSON
Disabled intents: None
Data path: /data
Metadata file: /usr/local/share/Red-DiscordBot/config.json

Message #bot-setup

**Comment by flaree** [comment]
run `pipinstall tabulate`, will fix soon

**Comment by flaree** [comment]
fixed in latest commit
