### ISSUE TITLE
Fatal issue - Cog not working

### ISSUE THREAD

**Issue by KwasiYaw** [flaree/flare-cogs#182]
**Cog will not work**
Upon loading the cog, adding logged commands ect. the cog will not work.
The console will spit out the following error:
`
Traceback (most recent call last):
  File "C:\Users\----\redenv\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\----\AppData\Local\Red-DiscordBot\Red-DiscordBot\data\remember\cogs\CogManager\cogs\cmdlogger\core.py", line 210, in on_command_completion
    and (conf["ignore_owners"] and await ctx.bot.is_owner(ctx.author))
KeyError: 'ignore_owners'
`
**Output of [p]help CogName and [p]debuginfo**
![image](https://user-images.githubusercontent.com/122640534/212400350-51695587-e1d9-4473-9114-2090d04fdba3.png)
![image](https://user-images.githubusercontent.com/122640534/212400514-2dcbc7e8-e1d2-4627-a1e5-8cea404fab86.png)

**Comment by flaree** [comment]
Wrong repo.

**Comment by KwasiYaw** [comment]
My bad
