### ISSUE TITLE
[giveaways] Error in command 'giveaway integrations' when bot is missing permissions.

### ISSUE THREAD

**Issue by Skyridr** [flaree/flare-cogs#183]
**Describe the bug**
When running the command [p]giveaway integrations and the bot is lacking permissions, error will occur.

```py
Exception in command 'giveaway integrations'
Traceback (most recent call last):
  File "/home/kirstin/kirstin/lib/python3.9/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/kirstin/kirstin/cogs/CogManager/cogs/giveaways/giveaways.py", line 507, in integrations
    await ctx.send(embed=embed)
  File "/home/kirstin/kirstin/lib/python3.9/site-packages/redbot/core/commands/context.py", line 93, in send
    return await super().send(content=content, **kwargs)
  File "/home/kirstin/kirstin/lib/python3.9/site-packages/discord/abc.py", line 1065, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed,
  File "/home/kirstin/kirstin/lib/python3.9/site-packages/discord/http.py", line 248, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kirstin/kirstin/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/kirstin/kirstin/lib/python3.9/site-packages/redbot/core/commands/commands.py", line 832, in invoke
    await super().invoke(ctx)
  File "/home/kirstin/kirstin/lib/python3.9/site-packages/discord/ext/commands/core.py", line 1348, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "/home/kirstin/kirstin/lib/python3.9/site-packages/discord/ext/commands/core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/kirstin/kirstin/lib/python3.9/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: Forbidden: 403 Forbidden (error code: 50013): Missing Permissions
```

Easy solution, but sharing it here as I assume no exception has been set with the command :).

**Comment by flaree** [comment]
closed with 3e63c313385dc9410e32f13aeb8c54df5353039f
