### ISSUE TITLE
Giveaways not loading in Red 3.5.4

### ISSUE THREAD

**Issue by SickProdigy** [flaree/flare-cogs#202]
**Describe the bug**
When trying to load giveaways throwing error for dateparser.

**Output of [p]help CogName and [p]debuginfo**

Logs:
[2023-08-20 18:39:01] [ERROR] red: Package loading failed
Traceback (most recent call last):
  File "/home/terry/redenv/lib/python3.11/site-packages/redbot/core/core_commands.py", line 188, in _load
    await bot.load_extension(spec)
  File "/home/terry/redenv/lib/python3.11/site-packages/redbot/core/bot.py", line 1680, in load_extension
    lib = spec.loader.load_module()
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 605, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1120, in load_module
  File "<frozen importlib._bootstrap_external>", line 945, in load_module
  File "<frozen importlib._bootstrap>", line 290, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 721, in _load
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/terry/Documents/python-bots/red-discord-cog/cogs/CogManager/cogs/giveaways/__init__.py", line 1, in <module>
    from .giveaways import Giveaways
  File "/home/terry/Documents/python-bots/red-discord-cog/cogs/CogManager/cogs/giveaways/giveaways.py", line 15, in <module>
    from .converter import Args
  File "/home/terry/Documents/python-bots/red-discord-cog/cogs/CogManager/cogs/giveaways/converter.py", line 4, in <module>
    import dateparser
ModuleNotFoundError: No module named 'dateparser'

# Debug Info for Red:

## System Metadata:
CPU Cores: 8 (x86_64)
RAM: 12.2GB/15.4GB (82.6%)

## OS variables:
OS version: Debian GNU/Linux 12
User: terry
Python executable: /home/terry/redenv/bin/python
Python version: 3.11.2 (64bit)
Pip version: 23.2.1
Red version: 3.5.4
Discord.py version: 2.3.2

## Red variables:
Instance name: SickGamingBot
Command line arguments: ['/home/terry/redenv/bin/python', '-O', '-m', 'redbot', 'SickGamingBot', '--no-prompt']
Global prefix(es): '-'
Owner(s): 228710499888398336 (sickprodigy)
Disabled intents: None
Storage type: JSON
Data path: /home/terry/Documents/python-bots/red-discord-cog
Metadata file: /home/terry/.config/Red-DiscordBot/config.json

**Comment by flaree** [comment]
Your bot failed to install the requirement, run [p]pipinstall dateparser
