### ISSUE TITLE
Hmmm, jsk shell seems doesn't work

### ISSUE THREAD

**Issue by OrdinaryEnder** [flaree/flare-cogs#229]
**Describe the bug**
Something going on when trying to use jsk shell.
```py
Traceback (most recent call last):
  File "/home/ordinaryender/.local/share/Red-DiscordBot/data/Aliya/cogs/Downloader/lib/jishaku/features/shell.py", line 45, in jsk_shell
    interface = PaginatorInterface(ctx.bot, paginator, owner=ctx.author)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ordinaryender/.local/share/Red-DiscordBot/data/Aliya/cogs/Downloader/lib/jishaku/shim/paginator_200.py", line 73, in __init__
    self.timeout = kwargs.pop('timeout', 7200)
    ^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/discord/ui/view.py", line 249, in timeout
    if self.__timeout_task is not None:
       ^^^^^^^^^^^^^^^^^^^
AttributeError: 'PaginatorInterface' object has no attribute '_View__timeout_task'

```

**Output of [p]help CogName and [p]debuginfo**
```
**cancel** Cancels a task with the given index.
**cat** Read out a file, using syntax highlighting if detected.
**curl** Download and display a text file from the internet.
**debug** Run a command timing execution and catching exceptions.
**dis** Disassemble Python code into bytecode.
**git** Shortcut for 'jsk sh git'. Invokes the system shell.
**hide** Hides Jishaku from the help command.
**invite** Retrieve the invite URL for this bot.
**load** Loads or reloads the given extension names.
**override** Run a command with a different user, channel, or threa...
**permtrace** Calculates the source of granted or rejected permissi...
**pip** Shortcut for 'jsk sh pip'. Invokes the system shell.
**py** Direct evaluation of Python code.
**py_inspect** Evaluation of Python code with inspect information.
**repeat** Runs a command multiple times in a row.
**retain** Turn variable retention for REPL on or off.
**rtt** Calculates Round-Trip Time to the API.
**shell** Executes statements in the system shell.
**show** Shows Jishaku in the help command.
**shutdown** Logs this bot out.
**source** Displays the source code for a command.
**tasks** Shows the currently running jishaku tasks.
**unload** Unloads the given extension names.
**voice** Voice-related commands.
```
```md
# Debug Info for Red:
```
```md
## System Metadata:
``````
CPU Cores: 2 (x86_64)
RAM: 1008.5MB/1.9GB (66.8%)
```
```md
## OS variables:
``````
OS version: Arch Linux
User: ordinaryender

``````
Python executable: /usr/bin/python
Python version: 3.11.8 (64bit)
Pip version: 24.0

``````
Red version: 3.5.9
Discord.py version: 2.3.2
```
```md
## Red variables:
``````
Instance name: Aliya
Command line arguments: ['/usr/bin/python', '-O', '-m', 'redbot', 'Aliya', '--no-prompt', '--dev']
Global prefix(es): 'al!'
Owner(s): 796915832617828352 (ordinaryender)
Disabled intents: None
Storage type: JSON
Data path: /home/ordinaryender/.local/share/Red-DiscordBot/data/Aliya
Metadata file: /home/ordinaryender/.config/Red-DiscordBot/config.json
```

**Comment by flaree** [comment]
idk hasn't been supported since dpy 2.0 release

**Comment by OrdinaryEnder** [comment]
> jsk hasn't been supported since dpy 2.0 release

Gonna write a new update or something?

**Comment by flaree** [comment]
> > jsk hasn't been supported since dpy 2.0 release
> 
> 
> 
> Gonna write a new update or something?

nope
